### ISSUE TITLE
Add fluid.css to uioStyles shortcode

### ISSUE THREAD

**Issue by jhung** [fluid-project/eleventy-plugin-fluid#81]
## Describe the bug
UI Options requires some styling from `framework/core/css/fluid.css` in order to apply certain UIO styles. For example, focus contrast styling requires `fl-focus` which is a style found in `fluid.css`.

Otherwise it is up to the integrator to understand this relationship and to manually include `fluid.css`.

**Comment by jobara** [comment]
The complicating factor is that if you use Enactors_base you may not want fluid.css. Either we should have additional shortcodes for the base vs drop-in enacting for UIO or express an expectation that the plugin is configured for one or the other scenario. If we keep things as is, and have the plugin handle the drop-in enacting, fluid.css should be added to the shortcode.

**Comment by jobara** [comment]
Turns out we need fluid.css for UIO. The contrast adjuster makes use of the `fl-hidden-accessible` class which is provided by fluid.css.

**Comment by jobara** [comment]
While the above is true, the iframe includes a reference to fluid.css. It doesn't use the one supplied by the shortcode.

**Comment by greatislander** [comment]
@jobara So to be clear— is it needed outside the iframe? I would expect not.

**Comment by jobara** [comment]
> @jobara So to be clear— is it needed outside the iframe? I would expect not.

For the drop-in version it is, as the contrast themes style against `.fl-focus` which will provide focus styling for interactive elements. The base (CSS Custom Props) versions doesn't prescribe styling so that's something you'd need to take care of yourself. I don't think it's needed for that version.

As mentioned above the prefs editor itself needs fluid.css for `fl-hidden-accessible` but it sources that from the iframe so that is a non-issue for the shortcodes.
